### PR TITLE
add pipx install command & add swig hint

### PR DESCRIPTION
**Pull request by FLX-0x00**
To install DonPAPI with poetry or pipx, the package must be built locally. To correctly build the m2crypto dependency, you need to install the "swig" tool. It is available as a package for most distros out there.

### CODE REVIEW

**Comment by zblurx** [comment]
Hey, swig is used for m2crypto, which is actually used by dead code.
Si I made a new branche called dep-fix in order to remove it, you can try this branch if you want

**Comment by FLX-0x00** [comment]
Oh that would be nice. Just wanted to get a path to install with pipx as I switched for python based offensive tools from packaging arch packages to simply use pipx. Thanks for the fast feedback and your help.

**Comment by zblurx** [comment]
Merged the branch dep-fix

**Comment by nightlark** [comment]
Just a note if it comes up in the future here or in another project - there is a [swig](https://pypi.org/project/swig/) PyPI package that can be used in the `build-system.requires` section of pyproject.toml which provides a pre-built copy of swig for Windows/Linux/macOS systems.

**Pull request closed without merging**
